// AUTO-GENERATED by scripts/apply-brand.js
// Do not edit manually. Run `npm run brand:apply <brand-id>` to regenerate.

import type { BrandConfig } from './brand-types';

export const BRAND_CONFIG: BrandConfig = {
  id: 'open-cowork',
  productName: 'Open Cowork',
  appId: 'com.opencowork.app',
  copyright: 'Copyright © 2026 Open Cowork Team',
  colors: {
    primary: '#2563EB',
    primaryHover: '#1D4ED8',
    accent: '#F59E0B',
    background: '#F8FAFC',
    surface: '#FFFFFF',
    sidebarActiveBg: '#2563EB',
    sidebarActiveText: '#FFFFFF',
    textPrimary: '#111827',
    textSecondary: '#6B7280',
  },
  features: {
    gradientTitles: false,
  },
  assets: {
    iconMac: 'icon.icns',
    iconWin: 'icon.ico',
    iconLinux: 'icon.png',
    tray: 'tray-icon.png',
    trayMac: 'tray-iconTemplate.png',
    trayWin: 'tray-icon.ico',
    logo: 'logo.png',
  },
};

export const BRAND_ID = BRAND_CONFIG.id;
export const BRAND_NAME = BRAND_CONFIG.productName;
export const BRAND_APP_ID = BRAND_CONFIG.appId;
export const BRAND_COPYRIGHT = BRAND_CONFIG.copyright;
